use-sort:
    sort-type: alph
    sort-direction: asc

header: |
    /**
     * Copyright 2016-2020, Snagshout <developers@snagshout.com>
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     *
     * This file is part of the Merchant package
     */
